[wokwi]
version = 1
firmware = 'build/flasher_args.json'
elf = 'build/sta.elf'
rfc2217ServerPort = 4000

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"